settings:
  base:
    APP_DISPLAY_NAME: CIVCOM
    PRODUCTION_APP_NAME: CIVCOM
    APP_GROUP_IDENTIFIER: group.pl.gov.psp.civcom
    BASE_BUNDLE_IDENTIFIER: pl.gov.psp.civcom
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
    DEVELOPMENT_TEAM: L643PDVV68
    IS_NIGHTLY_BUILD: false

    CLASSIC_APP_GROUP_IDENTIFIER: ""
    CLASSIC_APP_KEYCHAIN_SERVICE_IDENTIFIER: ""
    CLASSIC_APP_KEYCHAIN_ACCESS_GROUP_IDENTIFIER: ""
    CLASSIC_APP_DEEP_LINK_URL: ""
